# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  googleworkspace-cli = {
    pname = "googleworkspace-cli";
    version = "0.22.5";
    src = fetchurl {
      url = "https://github.com/googleworkspace/cli/releases/download/v0.22.5/google-workspace-cli-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-HSqf/VvJssLEtIYw2vCC+tE9nlfXQZiKLCSO7VYvfaw=";
    };
  };
  salesforce-cli = {
    pname = "salesforce-cli";
    version = "2.131.7";
    src = fetchurl {
      url = "https://registry.npmjs.org/@salesforce/cli/-/cli-2.131.7.tgz";
      sha256 = "sha256-Gz/ivDrEKNJO0JpbGNUCulPVSKnCucUfUc1RYMFtBko=";
    };
  };
  chrome-devtools-mcp = {
    pname = "chrome-devtools-mcp";
    version = "0.23.0";
    src = fetchFromGitHub {
      owner = "ChromeDevTools";
      repo = "chrome-devtools-mcp";
      rev = "chrome-devtools-mcp-v0.23.0";
      sha256 = "sha256-IK+cvZilMmrVPCPPpd7+jYNrzeXVgiXc6opOLthzFZM=";
    };
  };
  playwright-mcp = {
    pname = "playwright-mcp";
    version = "0.0.71";
    src = fetchFromGitHub {
      owner = "microsoft";
      repo = "playwright-mcp";
      rev = "v0.0.71";
      sha256 = "sha256-C4tXXpIbGdgedy5IdUi2xeSQwAo4v+++PC7rznX2sMc=";
    };
  };
}
